spring:
  application.name: bankApp

  datasource:
    url: jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update   # create-drop / update / validate selon besoin
    #show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/bank-realm



